[features]
seeds = false
skip-lint = false
[programs.localnet]
amm_anchor = "58hiw2qGCoDbqCiKvhzB9eiX3JkL8D6Q1BNUvJpTbKgN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/savvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
